### ISSUE TITLE
Todo Brain Dump

### ISSUE THREAD

**Issue by floooh** [floooh/sokol-nim#14]
- [x] code-generate the array-converter helpers
- [x] get rid of handwritten "extras" files entirely
- [x] GH Action test build
- [x] Windows: detect compiler for linker options
- [x] sokol-shdc: nim output
- [x] ~~make sapp.Keycode items uppercase~~ ~~make enum {.pure.}~~ add prefix to enum items, otherwise this can happen: https://twitter.com/FlohOfWoe/status/1540409023224315905
- [x] ~~use same approach for sokol_glue.h as in the zig bindings~~
- [x] update samples to what's in sokol-zig
- [x] ~~need a formatted print override for sdtx.printf()~~
- [x] ~~the sokol-app event callback appears to allow writing to the Event arg (no const ptr)~~ (see: https://github.com/floooh/sokol-nim/issues/18)
- [x] ~~need a slice-to-range converter (see buffer update in instancing.nim)~~
- [x] the to_Range() often doesn't do what's expected (for instance when used on a slice)
- [x] test on Windows D3D11
- [x] test on Windows GL
- [x] test on macOS Metal
- [x] test on macOS GL
- [x] test on Linux

NOTE: slices in Nim are quite useless for efficiently "slicing out" an array range,  because the slice operation creates a copy. Maybe experimental views can help somehow: https://nim-lang.org/docs/manual_experimental.html#view-types

**Comment by floooh** [comment]
Rendering problems on my Ubuntu laptop (specific to Nim, doesn't happen in the C version):

In blend demo, the background is sometimes black, and sometimes the expected quads are shown but are not moving:
![Screenshot from 2022-06-27 20-59-50](https://user-images.githubusercontent.com/1699414/176015795-6acc3976-5cd5-4ca5-9c0f-bb5b9b7ce46f.png)

In the MRT sample, the composed cube looks wrong (there composed cube doesn't have the RGB render targets shifted by offset):
![Screenshot from 2022-06-27 21-02-10](https://user-images.githubusercontent.com/1699414/176016194-38bdff43-6325-41a2-9361-139b98fbff46.png)

...looks like a problem with shader uniforms? => check code-generated structs!

**Comment by floooh** [comment]
...the shader uniform problem is somehow caused by the to_Range converter.

Basically this works:

```nim
sg.Range(pointer: vsparams.unsafeAddr, size: vsparams.sizeof.uint)
```
...but this doesn't:
```nim
sg.Range(fsqParams)
```
The second statement goes through the to_Range() converter. The pointer in the second range points to invalid data, and it's also different than the pointer of the original fsqParams object. I think the fsqParams object is copied, the pointer is taken, and then the copy is destroyed so that the pointer is dangling.

...it's interesting that this is only a problem in rare cases.
